### ISSUE TITLE
module 'pygrep' has no attribute 'grep'

### ISSUE THREAD

**Issue by ColinPitrat** [LaurentClaessens/pytex#1]
When trying to verify forward references in frido/giulietta with pytex, I have the following error:
Traceback (most recent call last):
1467  File "/home/travis/build/ColinPitrat/mazhe/pytex/pytex", line 678, in <module>
1468    RunMe(t)
1469  File "/home/travis/build/ColinPitrat/mazhe/pytex/pytex", line 667, in RunMe
1470    options.future_reference_verification(options)
1471  File "/home/travis/build/ColinPitrat/mazhe/pytex/pytex", line 369, in future_reference_verification
1472    A = pygrep.grep(re.escape(line_ref),
1473AttributeError: module 'pygrep' has no attribute 'grep'

This was after installing pygrep with pip.
Then I found:
./pytex/pytex:        import pygrep  # home made

So I realized the pygrep package from pip may not be the right one. I can't find any pygrep under pytex though, nor in your github repositories.

How is that supposed to work?

**Comment by ColinPitrat** [comment]
Without pygrep package installed, the error is 'module not found':
Traceback (most recent call last):
  File "pytex/pytex", line 678, in <module>
    RunMe(t)
  File "pytex/pytex", line 667, in RunMe
    options.future_reference_verification(options)
  File "pytex/pytex", line 280, in future_reference_verification
    import pygrep  # home made
ModuleNotFoundError: No module named 'pygrep'

**Comment by LaurentClaessens** [comment]
I published a patch to fix it. `pygrep` is a wheel I reinvented. I placed it somewhere on my filesystem. My bad.
In the same time, I get from 'python2' to 'python3'.

I should use 'pyenv' and create a venv to avoid this kind of problems.
